#! /usr/bin/env python3
# An RSS and Atom feed to email 'conversion' utility

# Copyright (C) 2015  Tomasz Kramkowski

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

import mail
import setup
import feeds

if __name__ == "__main__":
    global settings
    settings = setup.config()

    users = setup.users()
    feedconf = setup.feed_settings()
    subscriptions = setup.subscriptions(users)
    feed_list = setup.feeds(users, subscriptions, feedconf)

    feeds.grab(feed_list)
    mail.send(feed_list, settings)

    setup.save_feed_states(feed_list)
